/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    BaseCreateItem: typeof import('./src/components/BaseCreateItem.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    BaseTooltipButton: typeof import('./src/components/BaseTooltipButton.vue')['default']
    BlockTab: typeof import('./src/components/BlockTab.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ListContainer: typeof import('./src/components/ListContainer.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    ListItemOptions: typeof import('./src/components/ListItemOptions.vue')['default']
    ListItemWrapper: typeof import('./src/components/ListItemWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAuth: typeof import('./src/components/UserAuth.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
  }
}
