/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseAuth: typeof import('./src/components/BaseAuth.vue')['default']
    BaseCreateItem: typeof import('./src/components/BaseCreateItem.vue')['default']
    BaseEditItem: typeof import('./src/components/BaseEditItem.vue')['default']
    BaseEditOptions: typeof import('./src/components/BaseEditOptions.vue')['default']
    BaseItems: typeof import('./src/components/BaseItems.vue')['default']
    BaseList: typeof import('./src/components/BaseList.vue')['default']
    BaseListItem: typeof import('./src/components/BaseListItem.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    BaseUserMenu: typeof import('./src/components/BaseUserMenu.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
  }
}
